language: php
env:
  - DRUPAL_VERSION=7.78
php:
  - '7.1'
before_install:
  - cd ..
  - cp -R DrupalSqlSrvCI DrupalCI
install:
  - bash DrupalCI/src/travis/install.sh
#  - pecl install -d php_suffix=$TRAVIS_PHP_VERSION sqlsrv pdo_sqlsrv
  - export PATH="/opt/mssql-tools/bin:$PATH"
before_script:
  - bash DrupalCI/src/travis/build.sh
  - cd drupal-project
script:
  - php ./scripts/run-tests.sh --php `which php` "Database (SQL Server)"
