language: php
env:
  - DRUPAL_VERSION=7.78
php:
  - '7.4'
before_install:
  - cd ..
  - cp -R DrupalSqlSrvCI DrupalCI
install:
  - bash DrupalCI/src/travis/install.sh
  - export PATH="/opt/mssql-tools/bin:$PATH"
before_script:
  - bash DrupalCI/src/travis/build.sh
  - cd drupal-project
script:
  # test mssql version.
  # test php version.
  - php -m
  - VERSION=`php --version`
  - VERSION2="PHP ${TRAVIS_PHP_VERSION}*"
  - test "$VERSION" == "$VERSION2"
  # test apache settings.
  - apache2ctl -M
  # test drupal version
  - |
    if [ -z "$DRUPAL_VERSION" ] || [ "$DRUPAL_VERSION" == "7.x" ]; then
      VERSION=`git-branch --show-current`
      test "$VERSION" == "7.x"
    else
      VERSION=`git describe --tags --exact-match`
      test "$VERSION" == "$DRUPAL_VERSION"
    fi
  # integration test, run simpletests.
  - php ./scripts/run-tests.sh --php `which php` "Database (SQL Server)"
